language: go

go:
- 1.11.x

# calls goreleaser if commit is semvar tagged
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
